### ISSUE TITLE
Documentation of the roughness calculations

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/CABLE#73]
The roughness calculations are currently divided over four files in CABLE:

- [x]  cable_roughness.F90: module with 1 subroutine. Documentation in issue #45 
- [x] cbl_hgtAbove_snow.F90: 1 subroutine. Documentation in issue #71 
- [x] cbl_lai_eff.F90: 1 subroutine. Documentation in issue #72 
- [X] cbl_zetar.F90. Documentation in issue #78
- [x] cable_canopy.F90: some of the calculations have been placed in define_canopy subroutine. In our view, these should not be there. We may not document these at present as we'd rather prioritise restructuring the code.
